### PR TITLE
Fix infinite loop when iterating Query with rawResults is set

### PR DESCRIPTION
**Pull request by DonQueso89**
When retrieving Query results with rawResults set to True, the iterator never terminates because the IndexError signaling that there are no more items in self.result is caught in `__getitem__` and an empty list is returned. 

In stead of this, the error should propagate to `__next__` so that nextBatch is called and StopIteration is raised.

### CODE REVIEW

**Comment by tariqdaouda** [comment]
Thank you @DonQueso89, I think this has already been solved in an other PR. Let me know if you still encounter the same issue.

**Comment by DonQueso89** [comment]
Hey @tariqdaouda, yes I saw that pr but still submitted this one hoping that you would accept this one for being a better solution. In stead of handling the IndexError in two different places it would be better to have ‘__getitem__’ always let the caller handle the exception. This makes ‘__getitem__’ more transparent, easier to test and its behavior would be consistent regardless of the setting of rawResult

**Comment by tariqdaouda** [comment]
@DonQueso89  It would be great if you could a small test so we do not face the same problem again. I'll merge your PR them.

**Comment by DonQueso89** [comment]
> Waiting for a test.

@tariqdaouda added a basic test that covers the usage of SimpleQuery as a regular iterator

**Comment by DonQueso89** [comment]
@tariqdaouda will this still be merged?

**Comment by tariqdaouda** [comment]
Would you mind re sending the PR to the dev branch? That's where everything is integrated.

**Pull request closed without merging**
